# Generated by Django 5.0.4 on 2024-04-16 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=60)),
                ('password', models.CharField(max_length=40)),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
